### ISSUE TITLE
error when trying to add box art

### ISSUE THREAD

**Issue by Quakerjackers123** [KirovAir/TwilightBoxart#14]
Unhandled exception occured! System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at System.IO.Path.CombineNoChecks(String path1, String path2)
   at System.IO.StringResultHandler.CreateObject(SearchData searchData, WIN32_FIND_DATA& findData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at TwilightBoxart.BoxartCrawler.<DownloadArt>d__6.MoveNext() in C:\Users\Jesse\dev\TwilightBoxart\TwilightBoxart\BoxartCrawler.cs:line 44

it stops the process after this comes up and it does it everytime. it even happens on 0.6 as well.

**Comment by Linx-ESP** [comment]
Change the first directory (SD Root / Roms location) to [Letter]:\roms\nds and try again.
I also downloaded the NoIntro.db and TwitlightBoxart.ini from version 0.6, but seems to work without them too.

**Comment by KirovAir** [comment]
This crash is gone in the 2.0 rewrite: the scanner handles weird filenames now and one bad file can never stop the whole scan anymore. https://github.com/KirovAir/TwilightBoxart/releases/tag/2.0.0
