### ISSUE TITLE
Error macOS BigSur access .Spotlight-V100

### ISSUE THREAD

**Issue by tsuihak** [KirovAir/TwilightBoxart#6]
Every time I try to run in the MacOS BigSur terminal I get the error below. Do you know how I can solve it? I am using the latest version of your program.

genilsonsilva@MacBook-Pro-de-Genilson` TwilightBoxart-MacOS-CLI % ./TwilightBoxart.CLI

TwilightBoxart - Created by KirovAir.
Loads of love to the devs of TwilightMenu++, LibRetro, GameTDB and the maintainers of the No-Intro DB.

Loaded settings:
SDRoot / Roms location: 	/Volumes/NO NAME
BoxArt location: 		/Volumes/NO NAME/_nds/TWiLightMenu/boxart

Is this OK?
>Yes< /  No 

Started! Using width: 128 height: 115. Scanning /Volumes/NO NAME..
Searching art for BOOT.NDS.. 
Could not find boxart. (404)
Searching art for BOOT_cyclodsi.NDS.. 
Could not find boxart. (404)
Searching art for YSMenu.nds.. 
Could not find boxart. (404)
Searching art for _BOOT_DS.NDS.. 
Could not find boxart. (404)
Unhandled exception occured! System.UnauthorizedAccessException: Access to the path '/Volumes/NO NAME/.Spotlight-V100' is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.DequeueNextDirectory()
   at System.IO.Enumeration.FileSystemEnumerator`1.DirectoryFinished()
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at TwilightBoxart.BoxartCrawler.DownloadArt(IAppConfig downloadConfig) in C:\Users\Jesse\dev\TwilightBoxart\TwilightBoxart\BoxartCrawler.cs:line 44

**Comment by tsuihak** [comment]
Doing more tests here on MacOs and the same problem happened with the folder ".Trashes". It should cause the program to ignore those folders that start with "dot" since all of them on MacOs are system folders and also occur in the ".Spotlight-V100" folder. Congratulations on the program and I'm sorry for the English. I had to use Google Translator.

**Comment by KirovAir** [comment]
Hey, sorry for the late respone. I'll fix this in the next release and try to create some UI as well. ;)

**Comment by tsuihak** [comment]
Hey, how's it going? Any solution to this pointed error. I tried again today and the same thing happened. Please do not give up on me. hahahaha. I managed to edit the .ini file, thus placing the root of the SD, the place where the games are, so that it does not analyze the root and see those files that give errors.

; These are the default config values.
[Config]
SdRoot=/Volumes/NO NAME/roms/nds
BoxartPath=/Volumes/NO NAME/_nds/TWiLightMenu/boxart
SettingsPath={sdroot}/_nds/TWiLightMenu/settings.ini

Thanks.

**Comment by ilihasj** [comment]
To fix the no permission error on macOS, you need to give Terminal Full Disk Access. You can search Google to find a quick tutorial, or (on macOS Ventura):

1. Open System Settings
2. Go to Privacy & Security
3. Click "Full Disk Access"
4. Find "Terminal" in the list of applications
5. Toggle the button to give Terminal Full Disk Access

Afterwards, TwilightBoxart should run just fine.

**Comment by KirovAir** [comment]
Promised you a fix and some UI back then, took me a while but both happened. ;) TwilightBoxart 2.0 has a real macOS app, and system folders it can't read are skipped and reported instead of killing the scan: https://github.com/KirovAir/TwilightBoxart/releases/tag/2.0.0
